# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WS/axi_stream_tutorial/pynq_run/pynq_run.srcs/sources_1/bd/ZynqStream/ip/ZynqStream_doGain_0_0/ZynqStream_doGain_0_0.xci
# IP: The module: 'ZynqStream_doGain_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WS/axi_stream_tutorial/pynq_run/pynq_run.srcs/sources_1/bd/ZynqStream/ip/ZynqStream_doGain_0_0/constraints/doGain_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqStream_doGain_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/WS/axi_stream_tutorial/pynq_run/pynq_run.srcs/sources_1/bd/ZynqStream/ip/ZynqStream_doGain_0_0/ZynqStream_doGain_0_0.xci
# IP: The module: 'ZynqStream_doGain_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WS/axi_stream_tutorial/pynq_run/pynq_run.srcs/sources_1/bd/ZynqStream/ip/ZynqStream_doGain_0_0/constraints/doGain_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqStream_doGain_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
