# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZynqStream/ZynqStream.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream || ORIG_REF_NAME==ZynqStream} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_processing_system7_0_0/ZynqStream_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_processing_system7_0_0 || ORIG_REF_NAME==ZynqStream_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_doGain_0_0/ZynqStream_doGain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_doGain_0_0 || ORIG_REF_NAME==ZynqStream_doGain_0_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_xbar_0/ZynqStream_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_xbar_0 || ORIG_REF_NAME==ZynqStream_xbar_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_ps7_0_axi_periph_0/ZynqStream_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZynqStream_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_rst_ps7_0_100M_0/ZynqStream_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZynqStream_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_axi_dma_0_0/ZynqStream_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_axi_dma_0_0 || ORIG_REF_NAME==ZynqStream_axi_dma_0_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_axi_smc_0/ZynqStream_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_axi_smc_0 || ORIG_REF_NAME==ZynqStream_axi_smc_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_xlconcat_0_0/ZynqStream_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_xlconcat_0_0 || ORIG_REF_NAME==ZynqStream_xlconcat_0_0} -quiet] -quiet

# IP: bd/ZynqStream/ip/ZynqStream_auto_pc_0/ZynqStream_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqStream_auto_pc_0 || ORIG_REF_NAME==ZynqStream_auto_pc_0} -quiet] -quiet

# XDC: bd/ZynqStream/ZynqStream_ooc.xdc
